/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package tokobangunan;

import javax.swing.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Oki Firdaus Syah putra
 */
public class DashboardKaryawan extends javax.swing.JFrame {


    /** Creates new form DashboardKaryawan */
    public DashboardKaryawan() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bannerPOS = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        namaKaryawan = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JLabel();
        btnLogout = new javax.swing.JLabel();
        btnHistory = new javax.swing.JLabel();
        btnTransaksi = new javax.swing.JLabel();
        btnWarehouse = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CrafterPOS");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1360, 760));

        bannerPOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/banner.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(50, 130, 184));

        namaKaryawan.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        namaKaryawan.setForeground(new java.awt.Color(255, 255, 255));
        namaKaryawan.setText("namaKaryawan");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CrafterPOS-logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 931, Short.MAX_VALUE)
                .addComponent(namaKaryawan)
                .addGap(48, 48, 48))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(namaKaryawan))
                .addGap(36, 36, 36))
        );

        jPanel3.setBackground(new java.awt.Color(50, 130, 184));

        btnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-dashboard-secondary.png"))); // NOI18N
        //btnDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            //    public void mousePressed(java.awt.event.MouseEvent evt) {
                //        btnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokobangunan/img/btn-dashboard-secondary.png")));
                //    }
            //    public void mouseReleased(java.awt.event.MouseEvent evt) {
                //        btnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokobangunan/img/btn-dashboard-primary.png")));
                //    }
            //});
    btnDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            btnDashboardMouseClicked(evt);
        }
    });

    btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-logout-primary.png"))); // NOI18N
    btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mousePressed(java.awt.event.MouseEvent evt) {
            btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-logout-secondary.png")));
        }
        public void mouseReleased(java.awt.event.MouseEvent evt) {
            btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-logout-primary.png")));
        }
    });
    btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            btnLogoutMouseClicked(evt);
        }
    });

    btnHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-history-primary.png"))); // NOI18N
    btnHistory.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mousePressed(java.awt.event.MouseEvent evt) {
            btnHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-history-secondary.png")));
        }
        public void mouseReleased(java.awt.event.MouseEvent evt) {
            btnHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-history-primary.png")));
        }
    });
    btnHistory.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            btnHistoryMouseClicked(evt);
        }
    });

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(btnDashboard)
        .addComponent(btnLogout)
        .addComponent(btnHistory)
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addComponent(btnDashboard)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnHistory)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnLogout)
            .addGap(0, 0, Short.MAX_VALUE))
    );

    btnTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-transaksi-primary.png"))); // NOI18N
    btnTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mousePressed(java.awt.event.MouseEvent evt) {
            btnTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-transaksi-secondary.png")));
        }
        public void mouseReleased(java.awt.event.MouseEvent evt) {
            btnTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-transaksi-primary.png")));
        }
    });
    btnTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            btnTransaksiMouseClicked(evt);
        }
    });

    btnWarehouse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-warehouse-primary.png"))); // NOI18N
    btnWarehouse.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mousePressed(java.awt.event.MouseEvent evt) {
            btnWarehouse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-warehouse-secondary.png")));
        }
        public void mouseReleased(java.awt.event.MouseEvent evt) {
            btnWarehouse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-warehouse-primary.png")));
        }
    });
    btnWarehouse.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            btnWarehouseMouseClicked(evt);
        }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(75, 75, 75)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(bannerPOS)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(btnTransaksi)
                    .addGap(18, 18, 18)
                    .addComponent(btnWarehouse)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(bannerPOS)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnWarehouse)
                        .addComponent(btnTransaksi))
                    .addGap(0, 88, Short.MAX_VALUE))
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
    );

    getAccessibleContext().setAccessibleName("CrafterPOS");

    pack();
    }// </editor-fold>//GEN-END:initComponents


    private String kodeProfileKaryawan = "";
    public void kodeProfile(String kode){

        try {
            String sql = "SELECT `kd_profil`, `nama`, `kd_akun`, `role` FROM `profil` WHERE kd_profil = '"+ kode +
                    "';";
            Connection conn = (Connection) Config.configDB();
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
            if (rs.next()) {
                String profil = rs.getString("kd_profil");
                if (profil.equals(kode)){
                    this.namaKaryawan.setText(rs.getString("nama"));
                    kodeProfileKaryawan = kode;
                }
            } else {
                JOptionPane.showMessageDialog(null, null);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }
    
    private void btnTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransaksiMouseClicked
        // TODO add your handling code here:
        String nama = this.namaKaryawan.getText();
        try {
            String sql =
                    "SELECT `kd_profil`, `nama`, `kd_akun`, `role` FROM `profil` WHERE nama = '"+ nama +
                            "';";
            Connection conn = (Connection) Config.configDB();
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
            Transaksi transaksi = new Transaksi();
            if (rs.next()) {
                String karyawanName = rs.getString("nama");
                if (karyawanName.equals(nama)){
                    transaksi.kodeProfile(rs.getString("kd_profil"));
                    transaksi.setVisible(true);
                    this.setVisible(false);
                }
                else {
                    JOptionPane.showMessageDialog(null, "Invalid");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Invalid");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnTransaksiMouseClicked

    private void btnWarehouseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnWarehouseMouseClicked
        // TODO add your handling code here:
        String nama = this.namaKaryawan.getText();
        try {
            String sql =
                    "SELECT `kd_profil`, `nama`, `kd_akun`, `role` FROM `profil` WHERE nama = '"+ nama +
                            "';";
            Connection conn = (Connection) Config.configDB();
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
            Warehouse warehouse = new Warehouse();
            if (rs.next()) {
                String karyawanName = rs.getString("nama");
                if (karyawanName.equals(nama)){
                    warehouse.kodeProfile(rs.getString("kd_profil"));
                    warehouse.setVisible(true);
                    this.setVisible(false);
                }
                else {
                    JOptionPane.showMessageDialog(null, "Invalid");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Invalid");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnWarehouseMouseClicked

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        new LoginPage().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDashboardMouseClicked

    private void btnHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistoryMouseClicked
        try {
            String sql = "SELECT * FROM `profil` WHERE kd_profil = '"+ kodeProfileKaryawan +"';";
            Connection conn = (Connection) Config.configDB();
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
            if (rs.next()) {
                RiwayatTransaksi historyTransaction = new RiwayatTransaksi();
                String nama = rs.getString("nama");
                String role = rs.getString("role");
                if (role.equals("admin")){
                    historyTransaction.kodeProfile(rs.getString("kd_profil"));
                    historyTransaction.setVisible(true);
                    this.setVisible(false);
                }
                else if (role.equals("kasir")) {
                    historyTransaction.kodeProfile(rs.getString("kd_profil"));
                    historyTransaction.setVisible(true);
                    this.setVisible(false);
                }
                else {
                    JOptionPane.showMessageDialog(null, "Invalid");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Invalid");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnHistoryMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardKaryawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bannerPOS;
    private javax.swing.JLabel btnDashboard;
    private javax.swing.JLabel btnHistory;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JLabel btnTransaksi;
    private javax.swing.JLabel btnWarehouse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JLabel namaKaryawan;
    // End of variables declaration//GEN-END:variables

}
