/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tokobangunan;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

import tokobangunan.Components.RoundJTextField;
import tokobangunan.Components.RoundedPanel;

/**
 *
 * @author Oki Firdaus
 */
public class RiwayatTransaksi extends javax.swing.JFrame {

    /**
     * Creates new form RiwayatTransaksi
     */

    public void trTable() {

        DefaultTableModel tblTransaksi = new DefaultTableModel();
        tblTransaksi.addColumn("Kode transaksi");
        tblTransaksi.addColumn("Tanggal");
        tblTransaksi.addColumn("Nama Karyawan");
        tblTransaksi.addColumn("Harga");

        try {
            Statement st = (Statement) Config.configDB().createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM transaksi");

            while (rs.next()) {
                tblTransaksi.addRow(new Object[] {
                        rs.getString("kd_transaksi"),
                        rs.getString("tanggal"),
                        rs.getString("nama"),
                        rs.getString("harga_total"),
                });
                transactionTable.setModel(tblTransaksi);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }

    public void dtrTable(String kdTransaksi) {
        DefaultTableModel tblDetail = new DefaultTableModel();
        tblDetail.addColumn("Kode Transaksi");
        tblDetail.addColumn("Barang");
        tblDetail.addColumn("Harga");
        tblDetail.addColumn("Kuantitas");
        tblDetail.addColumn("Harga Total");
        tblDetail.addColumn("Karyawan");

        try {
            Statement st = (Statement) Config.configDB().createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM `detail_transaksi` JOIN transaksi ON detail_transaksi" +
                    ".kd_transaksi = transaksi.kd_transaksi WHERE transaksi.kd_transaksi = '"+ kdTransaksi +"';");

            while (rs.next()) {
                tblDetail.addRow(new Object[] {

                        rs.getString("kd_transaksi"),
                        rs.getString("nama_barang"),
                        rs.getString("harga_satuan"),
                        rs.getString("kuantitas"),
                        rs.getString("harga_total"),
                        rs.getString("nama"),
                });
                detailTransactionTable.setModel(tblDetail);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    public RiwayatTransaksi() {
        initComponents();
        trTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JLabel();
        btnLogout = new javax.swing.JLabel();
        btnHistory = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        namaKaryawan = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new RoundedPanel(10, new Color(187, 225, 250));
        jScrollPane1 = new javax.swing.JScrollPane();
        transactionTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        searchField = new RoundJTextField(4);
        btnSearch = new javax.swing.JLabel();
        jPanel6 = new RoundedPanel(10, new Color(187, 225, 250));
        jScrollPane2 = new javax.swing.JScrollPane();
        detailTransactionTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CrafterPOS");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1360, 760));

        jPanel4.setBackground(new java.awt.Color(50, 130, 184));

        btnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-dashboard-primary.png"))); // NOI18N
        btnDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-dashboard-secondary.png")));
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-dashboard-primary.png")));
            }
        });
        btnDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDashboardMouseClicked(evt);
            }
        });

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-logout-primary.png"))); // NOI18N
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-logout-secondary.png")));
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-logout-primary.png")));
            }
        });
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });

        btnHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-history-secondary.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDashboard)
            .addComponent(btnLogout)
            .addComponent(btnHistory)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(btnDashboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHistory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogout)
                .addGap(0, 348, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(50, 130, 184));

        namaKaryawan.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        namaKaryawan.setForeground(new java.awt.Color(255, 255, 255));
        namaKaryawan.setText("namaKaryawan");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CrafterPOS-logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 931, Short.MAX_VALUE)
                .addComponent(namaKaryawan)
                .addGap(48, 48, 48))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(namaKaryawan))
                .addGap(36, 36, 36))
        );

        jPanel5.setBackground(null);

        transactionTable.getTableHeader().setFont(new java.awt.Font("Lato", 1, 14));
        transactionTable.setBackground(null);
        transactionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Transaksi", "Tanggal", "Nama Karyawan", "Harga"
            }
        ));
        transactionTable.setGridColor(new java.awt.Color(187, 225, 250));
        transactionTable.setShowGrid(false);
        transactionTable.setOpaque(false);
        ((DefaultTableCellRenderer)transactionTable.getDefaultRenderer(Object.class)).setOpaque(false);
        transactionTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transactionTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(transactionTable);
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);

        jLabel6.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        jLabel6.setText("Cari Transaksi");

        searchField.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        searchField.setForeground(new java.awt.Color(82, 97, 107));

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_search_primary.png"))); // NOI18N
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_search_secondary.png")));
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_search_primary.png")));
            }
        });
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 989, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchField)
                .addGap(18, 18, 18)
                .addComponent(btnSearch)
                .addGap(37, 37, 37))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel6.setBackground(null);

        detailTransactionTable.getTableHeader().setFont(new java.awt.Font("Lato", 1, 14));
        detailTransactionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Transaksi", "Barang", "Harga", "Kuantitas", "Harga Total", "Karyawan"
            }
        ));
        detailTransactionTable.setGridColor(new java.awt.Color(187, 225, 250));
        detailTransactionTable.setShowGrid(false);
        detailTransactionTable.setOpaque(false);
        ((DefaultTableCellRenderer)detailTransactionTable.getDefaultRenderer(Object.class)).setOpaque(false);
        jScrollPane2.setViewportView(detailTransactionTable);
        jScrollPane2.setOpaque(false);
        jScrollPane2.getViewport().setOpaque(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getAccessibleContext().setAccessibleName("CrafterPOS");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String kodeProfileKaryawan = "";
    public void kodeProfile(String kode){

        try {
            String sql = "SELECT `kd_profil`, `nama`, `kd_akun`, `role` FROM `profil` WHERE kd_profil = '"+ kode +
                    "';";
            Connection conn = (Connection) Config.configDB();
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
            if (rs.next()) {
                String profil = rs.getString("kd_profil");
                if (profil.equals(kode)){
                    this.namaKaryawan.setText(rs.getString("nama"));
                    kodeProfileKaryawan = kode;
                }
            } else {
                JOptionPane.showMessageDialog(null, null);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }
    
    private void btnDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMouseClicked
        // TODO add your handling code here:
        try {
            String sql = "SELECT * FROM `profil` WHERE kd_profil = '"+ kodeProfileKaryawan +"';";
            Connection conn = (Connection) Config.configDB();
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
            if (rs.next()) {
                DashboardKaryawan DashKaryawan = new DashboardKaryawan();
                DashboardAdmin DashAdmin = new DashboardAdmin();
                String nama = rs.getString("nama");
                String role = rs.getString("role");
                if (role.equals("admin")){
                    DashAdmin.kodeProfile(rs.getString("kd_profil"));
                    DashAdmin.setVisible(true);
                    this.setVisible(false);
                }
                else if (role.equals("kasir")) {
                    DashKaryawan.kodeProfile(rs.getString("kd_profil"));
                    DashKaryawan.setVisible(true);
                    this.setVisible(false);
                }
                else {
                    JOptionPane.showMessageDialog(null, "Invalid");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Invalid");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnDashboardMouseClicked

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        // TODO add your handling code here:
        new LoginPage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        String search = searchField.getText();
        DefaultTableModel tblTransaksi = new DefaultTableModel();
        tblTransaksi.addColumn("Kode transaksi");
        tblTransaksi.addColumn("Tanggal");
        tblTransaksi.addColumn("Nama Karyawan");
        tblTransaksi.addColumn("Harga");
        try {
            String sql = "SELECT * FROM `transaksi` WHERE kd_transaksi = '"+search +"';";
            Connection conn = (Connection) Config.configDB();
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
            if (rs.next()) {
                tblTransaksi.addRow(new Object[] {
                        rs.getString("kd_transaksi"),
                        rs.getString("tanggal"),
                        rs.getString("nama"),
                        rs.getString("harga_total"),
                });
                transactionTable.setModel(tblTransaksi);
            } else {
                JOptionPane.showMessageDialog(null, "Transaksi tidak Ditemukan");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_btnSearchMouseClicked

    private void transactionTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transactionTableMouseClicked
        int row = transactionTable.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) transactionTable.getModel();
        String kodeProfil = model.getValueAt(row, 0).toString();
        dtrTable(kodeProfil);
    }//GEN-LAST:event_transactionTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RiwayatTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RiwayatTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RiwayatTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RiwayatTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RiwayatTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel btnDashboard;
    private javax.swing.JLabel btnHistory;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JLabel btnSearch;
    private javax.swing.JTable detailTransactionTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel namaKaryawan;
    private javax.swing.JTextField searchField;
    private javax.swing.JTable transactionTable;
    // End of variables declaration//GEN-END:variables
}
